### ISSUE TITLE
panic runtime error: slice bounds out of range in n2kMessageReceived

### ISSUE THREAD

**Issue by asbjorn** [timmathews/argo#5]
Hi!

I'm having a runtime error popping up every now and then. It might be my Actisense / GPS device that is giving some corrupt data or something, but I still think the code should handle it.

The runtime error is as follows:

```go
panic: runtime error: slice bounds out of range [:36] with capacity 31                                                                                                                        
goroutine 6 [running]:                                                                                                                                                                        
github.com/timmathews/argo/actisense.n2kMessageReceived(0x1b2dc01, 0x16, 0x1f, 0x1, 0x1, 0x1)                                                                                                 
        /home/asbjorn/Projects/Moen_Marin/modbus-rtu-client/vendor/pkg/mod/github.com/timmathews/argo@v0.0.0-20181009003531-03c44b3fef04/actisense/actisense.go:220 +0x2fc                    
github.com/timmathews/argo/actisense.messageReceived(0x1b2dc00, 0x17, 0x20, 0x1, 0x1, 0x0)                                                                                                    
        /home/asbjorn/Projects/Moen_Marin/modbus-rtu-client/vendor/pkg/mod/github.com/timmathews/argo@v0.0.0-20181009003531-03c44b3fef04/actisense/actisense.go:190 +0x180                    
github.com/timmathews/argo/actisense.(*ActisensePort).Read(0x1992000, 0x18d22c0, 0x1f11a, 0x361bf0)                                                                                           
        /home/asbjorn/Projects/Moen_Marin/modbus-rtu-client/vendor/pkg/mod/github.com/timmathews/argo@v0.0.0-20181009003531-03c44b3fef04/actisense/actisense.go:118 +0x114                    
main.(*NavigationDevice).Run(0x1810080, 0x226c78, 0x190a5c0, 0x187ce80)                                                                                                                       
        /home/asbjorn/Projects/Moen_Marin/modbus-rtu-client/navi.go:192 +0xc8                                                                                                                 
created by main.main                                                                                                                                                                          
        /home/asbjorn/Projects/Moen_Marin/modbus-rtu-client/main.go:259 +0x964  
``` 

I've figured out that in `actisense.go:212` there is the `lth := msg[11]` and a following check to see if the `lth` value is too large. Next the code tries to extract the Data from the byte slice by first adding 12 to the `lth`variable, then attempt to read from `msg[12:lth]`. Now, the `msg[12:lth]` goes outside the byte slice and therefore causes the panic.

I think a simple check like this on `actisense.go:220` would fix the error:
```go
if int(lth) > len(msg) {
    return nil, errors.New(fmt.Sprintf("Ignore incorrect lth value", lth))
}
```

**Comment by timmathews** [comment]
Resolved by #6
